### ISSUE TITLE
Site down? 

### ISSUE THREAD

**Issue by cduguet** [benjamintd/chronotrains#39]
This seems to be a deployment issue more than a bug in the code. The website appears to be down:

![IMG_4816](https://github.com/benjamintd/chronotrains/assets/1536515/1556b97b-b837-4ee5-b10b-1f5427cca1d5)

might be due to the spike in traffic. 

UPDATE: Editing out the nonsense from iPhone autocorrect.

**Comment by ASAMedia** [comment]
Looks more like that the site got deleted or is offline.
On [Vercel.com](https://vercel.com/docs/errors/DEPLOYMENT_NOT_FOUND) it states:

> The DEPLOYMENT_NOT_FOUND error occurs when a request is made for a deployment that doesn't exist. This could happen if the deployment ID or URL is incorrect, or if the deployment has been deleted.

**Comment by benjamintd** [comment]
I had to disable the site because a traffic spike caused the cloud costs to
go higher than my ad revenue by a large amount. I'll optimize and republish
sometime this week.

**Comment by Misterodd** [comment]
Out of curiosity, how much does it cost normally and non-normally?

**Comment by cduguet** [comment]
[OFF TOPIC] 
Following the curiosity here as well: Isn't there a way to make sure revenue by ad impressions spikes together with the traffic demand? I always thought the best thing that can happen to ad-supported sites was to explode in popularity.

**Comment by benjamintd** [comment]
Unfortunately currently my cloud costs can spike non linearly with traffic.
It's more of an engineering and caching issue - but database timeouts can
increase costs significantly.
